import Link from "next/link";

export default function MethodologyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 md:px-6">
      <p className="font-mono text-[11px] uppercase tracking-[0.22em] text-accent">Methodology</p>
      <h1 className="mt-3 font-display text-4xl font-semibold tracking-tight">
        How the experiment works
      </h1>

      <section className="mt-10 space-y-3 text-ink/75">
        <h2 className="font-display text-2xl font-semibold text-ink">Dataset</h2>
        <p>
          Synthetic sensitive-information passages generated by{" "}
          <code className="font-mono text-sm">research/datasets/generate_sensitive_dataset.py</code>.
          Deterministic seeds, train/validation/test splits, adversarial negatives, redactions
          identifiers, and formatting noise. No real personal data.
        </p>
      </section>

      <section className="mt-10 space-y-3 text-ink/75">
        <h2 className="font-display text-2xl font-semibold text-ink">Graph construction</h2>
        <p>
          Demo mode uses a redistributable modular sparse graph (~512 nodes) with region labels and
          abstract 3D layouts. Optional research imports support hemibrain (CC BY) and FlyWire
          (CC BY-NC) via documented scripts. See{" "}
          <Link href="/about" className="text-accent underline-offset-2 hover:underline">
            About
          </Link>{" "}
          and <code className="font-mono text-sm">docs/DATA_AND_LICENSING.md</code>.
        </p>
      </section>

      <section className="mt-10 space-y-3 text-ink/75">
        <h2 className="font-display text-2xl font-semibold text-ink">Reservoir equations</h2>
        <pre className="overflow-x-auto border border-ink/15 bg-mist/40 p-4 font-mono text-xs">
{`x(t+1) = (1 - λ) x(t) + λ f(W x(t) + Win u(t))
W  : connectome-derived sparse matrix (spectral-radius scaled)
Win: fixed projection into selected input neurons
f  : tanh
λ  : leak`}
        </pre>
        <p>
          This is a computational reservoir inspired by / mapped from connectome structure — not a
          claim of biological realism.
        </p>
      </section>

      <section className="mt-10 space-y-3 text-ink/75">
        <h2 className="font-display text-2xl font-semibold text-ink">Random controls</h2>
        <ul className="list-disc space-y-1 pl-5">
          <li>Random A: Erdős–Renyi-like sparse rewiring, matched node/edge count</li>
          <li>Random B: degree-preserving edge swaps</li>
          <li>Random C: fixed topology, randomized weights</li>
        </ul>
      </section>

      <section className="mt-10 space-y-3 text-ink/75">
        <h2 className="font-display text-2xl font-semibold text-ink">Training & statistics</h2>
        <p>
          Only the readout (or baseline classifier) is trained. Metrics include exact-match accuracy,
          macro F1, precision/recall, per-class scores, and binary sensitive detection confusion
          matrices. Comparisons use multiple seeds; intervals are reported when multiple runs exist.
        </p>
      </section>

      <section className="mt-10 space-y-3 text-ink/75">
        <h2 className="font-display text-2xl font-semibold text-ink">Limitations</h2>
        <ul className="list-disc space-y-1 pl-5">
          <li>Demo graph is synthetic, not anatomical.</li>
          <li>Synthetic PII patterns can be linearly separable — baselines may win.</li>
          <li>Hashing encoder is a convenience default; stronger encoders are optional.</li>
          <li>Browser visualization samples neurons; it does not render full synapse sets.</li>
        </ul>
      </section>

      <section className="mt-10 space-y-3 text-ink/75">
        <h2 className="font-display text-2xl font-semibold text-ink">Reproducibility</h2>
        <pre className="overflow-x-auto border border-ink/15 bg-mist/40 p-4 font-mono text-xs">
{`make generate-data
make train
make benchmark
make ablate`}
        </pre>
      </section>
    </div>
  );
}