import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {readGraph,hash} from './graph_io.mjs';
import {simulate,validateModel,predict,teach} from '../web/engine.mjs';
import {CASES,encodeFacts,makeCorpus} from '../web/cases.mjs';
const root=process.argv[2]||'dist',start=performance.now();
const {graph:g,manifest:m}=await readGraph(root);
assert.equal(g.n,166700);assert.equal(g.targets.length,25582938);assert.equal(m.coverage.retainedSynapticContacts,124177617);
assert.equal(m.coverage.isolatedNeurons,217);assert.equal(m.coverage.sourcePairs-m.coverage.excludedPairs,g.targets.length);
const bytes=await readFile(root+'/data/starter.json'),proof=JSON.parse(await readFile(root+'/data/model-manifest.json','utf8'));
assert.equal(hash(bytes),proof.sha256);
const model=validateModel(JSON.parse(bytes),{fingerprint:g.fingerprint,featureSize:576});
const x=encodeFacts(CASES[0].facts),a=await simulate(g,x),b=await simulate(g,x),quiet=await simulate(g,x.map(()=>0)),cut=await simulate(g,x,{severed:true});
assert.deepEqual(a.features,b.features);assert.ok(a.features.some(v=>v!==0));assert.ok(a.trace.at(-1).active>150000);assert.ok(quiet.state.every(v=>v===0));assert.ok(cut.features.every(v=>v===0));
let callbacks=0;await assert.rejects(simulate(g,x,{cancel:()=>callbacks>=3,onFrame:()=>callbacks++}),/cancel/i);assert.equal(callbacks,3);
const before=predict(model,a.features),updated=teach(model,a.features,(before.action+1)%8);assert.notDeepEqual(updated.weights,model.weights);assert.equal(updated.lessons,49);
const report=JSON.parse(await readFile(root+'/data/audit.json','utf8'));
assert.equal(report.fingerprint,g.fingerprint);assert.equal(report.rows.length,24);
for(const score of report.scores)assert.equal(score.correct,report.rows.filter(r=>r[score.key]===r.expected).length);
const heldOut=makeCorpus(42).test;assert.deepEqual(report.rows.map(r=>r.facts),heldOut.map(c=>c.facts));
const evidence={dataset:m.dataset,fingerprint:g.fingerprint,neurons:g.n,connections:g.targets.length,synapticContacts:m.coverage.retainedSynapticContacts,activeOnPetition:a.trace.at(-1).active,readoutDimensions:a.features.length,decision:before.action,deterministic:true,silenceIsZero:true,severedReadoutIsZero:true,cancellation:true,teachingChangesWeights:true,modelHashVerified:true,auditReconciled:true,milliseconds:performance.now()-start,processMemory:process.memoryUsage()};
await mkdir('results',{recursive:true});await writeFile('results/full-graph-verification.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));
